project:
  type: website
  output-dir: docs

website:
  title: "hopla"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/page1.qmd
        text: Page 1
      - href: pages/page2.qmd
        text: Page 2 avec plein de texte

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source
